// Design Tokens Configuration for Next.js
// Generated by design-tokens-sync

export default {
  tokens: {
    input: 'tokens.json',
    validation: {
      required: ['core.colors', 'core.spacing', 'core.typography'],
      optional: ['semantic', 'component']
    }
  },
  output: {
    css: 'styles/tokens.css',
    typescript: 'types/tokens.d.ts',
    // Prefer Tailwind presets instead of writing root config
    tailwindPresetEsm: 'tokens.tailwind.preset.js',
    tailwindPresetCjs: 'tokens.tailwind.preset.cjs',
    scss: 'styles/_tokens.scss',
    json: 'data/tokens.json',
    javascript: 'data/tokens.js',
    tokensCjs: 'data/tokens.cjs',
    shadcnThemeCss: 'styles/shadcn-theme.css'
    // Mobile platforms (added automatically based on init selection):
    // ios: 'platforms/ios/Colors.swift',
    // android: 'platforms/android/colors.xml',
    // xamarin: 'platforms/xamarin/Colors.xaml',
    // reactNative: 'platforms/reactNative/tokens.js',
    // flutter: 'platforms/flutter/design_tokens.dart',
    // kotlinCompose: 'platforms/kotlinCompose/DesignTokens.kt',
    // swiftui: 'platforms/swiftui/DesignTokens.swift'
  },
  nextjs: {
    // Next.js specific configuration
    appDir: true,  // App Router support
    pages: 'app',  // App directory structure
    components: 'components',
    styles: 'styles',
    cssModules: false,
    styledJsx: false
  },
  git: {
    enabled: true,
    autoCommit: true,
    autoPush: false,
    commitMessage: '🎨 Update design tokens'
  },
  analytics: {
    enabled: true,
    autoCollect: true,
    scanDirs: ['app/**/*', 'components/**/*', 'pages/**/*'],
    fileExtensions: ['.ts', '.tsx', '.js', '.jsx', '.css', '.scss', '.module.css'],
    outputDir: '.tokens-analytics'
  },
  watch: {
    enabled: true,
    ignore: ['node_modules', '.git', '.next', 'out', 'dist']
  },
  build: {
    // Next.js build integration
    beforeBuild: 'npm run tokens:sync',
    validateBeforeCommit: true,
    generateStatic: true
  }
}; 