/** @type {import('tailwindcss').Config} */
// Design Tokens - Auto-generated Tailwind Configuration
// Do not edit this file manually

export default {
  "theme": {
    "extend": {
      "colors": {
        "primary": {
          "50": "#F7E9F2",
          "100": "#F0D3E6",
          "200": "#E8BDD9",
          "300": "#E0A7CD",
          "400": "#D991C1",
          "500": "#673391",
          "600": "#76479B",
          "700": "#835AA5",
          "800": "#926EB0",
          "900": "#4F286F"
        },
        "accent": {
          "50": "#F7E9F2",
          "100": "#F0D3E6",
          "200": "#E8BDD9",
          "300": "#E0A7CD",
          "400": "#D991C1",
          "500": "#B22382",
          "600": "#BA398F",
          "700": "#C965A7",
          "800": "#7A1057",
          "900": "#7A1057"
        },
        "success": {
          "50": "#E6F4EC",
          "100": "#2D8659",
          "200": "#51A037",
          "300": "#3E7D2B"
        },
        "warning": {
          "50": "#FFF8E1",
          "100": "#FF9800"
        },
        "error": {
          "50": "#FCF0EE",
          "100": "#CA7373",
          "200": "#FAEDED",
          "300": "#A22F2F"
        },
        "neutral": {
          "50": "#FFFFFF",
          "100": "#FAFAFA",
          "200": "#F3F8FC",
          "300": "#F0F6FA",
          "400": "#FAFDFF",
          "500": "#E7EDF0",
          "600": "#909BAA",
          "700": "#757575",
          "800": "#708497",
          "900": "#000000"
        },
        "status": {
          "success": {
            "background": {
              "value": "#E6F4EC",
              "type": "color"
            },
            "text": {
              "value": "#2D8659",
              "type": "color"
            },
            "border": {
              "value": "#51A037",
              "type": "color"
            }
          },
          "warning": {
            "background": {
              "value": "#FFF8E1",
              "type": "color"
            },
            "text": {
              "value": "#FF9800",
              "type": "color"
            }
          },
          "error": {
            "background": {
              "value": "#FCF0EE",
              "type": "color"
            },
            "text": {
              "value": "#CA7373",
              "type": "color"
            },
            "border": {
              "value": "#A22F2F",
              "type": "color"
            }
          },
          "info": {
            "background": {
              "value": "#F7E9F2",
              "type": "color"
            },
            "text": {
              "value": "#C965A7",
              "type": "color"
            }
          },
          "verified": {
            "background": {
              "value": "#51A037",
              "type": "color"
            },
            "text": {
              "value": "#FFFFFF",
              "type": "color"
            }
          }
        },
        "text": {
          "primary": "#673391",
          "secondary": "#757575",
          "tertiary": "#909BAA",
          "inverse": "#FFFFFF",
          "muted": "#708497",
          "success": "#2D8659",
          "warning": "#FF9800",
          "error": "#CA7373"
        },
        "background": {
          "primary": "#F7E9F2",
          "secondary": "#FFFFFF",
          "tertiary": "#F3F8FC",
          "inverse": "#673391",
          "surface": "#FFFFFF",
          "overlay": "rgba(0, 0, 0, 0.75)"
        },
        "border": {
          "default": "#E7EDF0",
          "hover": "#D991C1",
          "focus": "#673391",
          "light": "#E7EDF0",
          "success": "#51A037",
          "error": "#CA7373"
        },
        "brand": {
          "primary": "#673391",
          "secondary": "#76479B",
          "tertiary": "#E8BDD9",
          "accent": "#B22382"
        }
      },
      "spacing": {
        "0": "0",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "8": "2rem",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem"
      },
      "borderRadius": {
        "none": "0",
        "sm": "0.125rem",
        "base": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      "fontFamily": {
        "primary": [
          "Roboto",
          "system-ui",
          "sans-serif"
        ],
        "secondary": [
          "DM Sans",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "Fira Code",
          "Monaco",
          "Consolas",
          "monospace"
        ]
      },
      "fontSize": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem"
      },
      "fontWeight": {
        "normal": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700"
      },
      "lineHeight": {
        "tight": "1.22",
        "normal": "1.5",
        "relaxed": "1.75"
      },
      "boxShadow": {
        "sm": "0px 1px 2px 0px rgba(0, 0, 0, 0.06), 0px 1px 3px 0px rgba(0, 0, 0, 0.1)",
        "base": "0px 1px 3px 0px rgba(0, 0, 0, 0.1), 0px 1px 2px -1px rgba(0, 0, 0, 0.1)",
        "md": "0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -2px rgba(0, 0, 0, 0.1)",
        "lg": "0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -4px rgba(0, 0, 0, 0.1)",
        "xl": "0px 20px 25px -5px rgba(0, 0, 0, 0.1), 0px 8px 10px -6px rgba(0, 0, 0, 0.1)"
      },
      "opacity": {
        "0": "0",
        "25": "0.25",
        "50": "0.5",
        "75": "0.75",
        "100": "1"
      },
      "zIndex": {
        "auto": 0,
        "base": 1,
        "dropdown": 1000,
        "modal": 1040,
        "popover": 1050,
        "tooltip": 1060
      },
      "transitionDuration": {
        "fast": "150ms",
        "normal": "300ms",
        "slow": "500ms"
      },
      "transitionTimingFunction": {
        "linear": "linear",
        "ease": "ease",
        "ease-in": "ease-in",
        "ease-out": "ease-out",
        "ease-in-out": "ease-in-out"
      },
      "screens": {
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1536px"
      }
    }
  }
};
