/** @type {import('tailwindcss').Config} */
// Design Tokens - Auto-generated Tailwind Configuration
// Do not edit this file manually

export default {
  "theme": {
    "extend": {
      "colors": {
        "identisafe-identisafe-lighter": "#00ff5c",
        "identisafe-identisafe-light": "#00e352",
        "identisafe-identisafe": "#00b140",
        "identisafe-identisafe-dark": "#7d6e00",
        "identisafe-identisafe-darker": "#004a1b",
        "red-red": "#ef5350",
        "red-red-light": "#ef9897",
        "red-red-dark": "#bd423f",
        "yellow-yellow": "#ffbf00",
        "yellow-yellow-light": "#ffe699",
        "yellow-yellow-dark": "#cc9900",
        "green-green": "#419645",
        "green-green-light": "#62e368",
        "green-green-dark": "#2b632e",
        "blue-blue": "#2196f3",
        "blue-blue-light": "#6ec6ff",
        "blue-blue-dark": "#0069c0",
        "grey-grey-0": "#000000",
        "grey-grey-10": "#212121",
        "grey-grey-20": "#303030",
        "grey-grey-30": "#424242",
        "grey-grey-40": "#616161",
        "grey-grey-50": "#757575",
        "grey-grey-60": "#9e9e9e",
        "grey-grey-70": "#bdbdbd",
        "grey-grey-80": "#e0e0e0",
        "grey-grey-90": "#f5f5f5",
        "grey-grey-100": "#ffffff",
        "neon-neon": "#baff29",
        "neon-neon-light": "#ebffc2",
        "neon-neon-dark": "#82b21d"
      },
      "spacing": {
        "100": "0.125rem",
        "200": "0.25rem",
        "300": "0.5rem",
        "400": "0.75rem",
        "500": "1rem",
        "600": "1.5rem",
        "700": "2rem",
        "800": "3rem",
        "900": "4rem",
        "1000": "8rem"
      },
      "borderRadius": {
        "none": "0rem",
        "xs": "0.25rem",
        "sm": "0.5rem",
        "md": "1.5rem",
        "lg": "2rem",
        "xxs": "0.125rem",
        "xl": "4rem"
      },
      "fontFamily": {
        "font-family-1": "Noto Sans",
        "font-family-2": "Apfel Grotesk"
      },
      "fontSize": {
        "font-size-100-10": "0.625rem",
        "font-size-200-12": "0.75rem",
        "font-size-300-14": "0.875rem",
        "font-size-400-16": "1rem",
        "font-size-500-20": "1.25rem",
        "font-size-600-24": "1.5rem",
        "font-size-700-32": "2rem",
        "font-size-800-40": "2.5rem",
        "font-size-900-48": "3rem",
        "font-size-1000-60": "3.75rem"
      },
      "fontWeight": {
        "font-weight-regular": "25rem",
        "font-weight-medium": "31.25rem",
        "font-weight-semibold": "37.5rem",
        "font-weight-bold": "43.75rem"
      },
      "lineHeight": {
        "font-line-height-800": "3rem",
        "font-line-height-700": "2.5rem",
        "font-line-height-600": "2rem",
        "font-line-height-500": "1.5rem",
        "font-line-height-400": "1.25rem",
        "font-line-height-300": "1rem",
        "font-line-height-200": "0.875rem",
        "font-line-height-100": "0.75rem"
      },
      "boxShadow": {
        "sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "md": "0 4px 6px -1px rgb(0 0 0 / 0.1)",
        "lg": "0 10px 15px -3px rgb(0 0 0 / 0.1)",
        "xl": "0 20px 25px -5px rgb(0 0 0 / 0.1)"
      },
      "opacity": {
        "0": "0",
        "25": "0.25",
        "50": "0.5",
        "75": "0.75",
        "100": "1"
      },
      "zIndex": {
        "auto": 0,
        "base": 1,
        "dropdown": 1000,
        "modal": 1040,
        "popover": 1050,
        "tooltip": 1060
      },
      "transitionDuration": {
        "fast": "150ms",
        "normal": "300ms",
        "slow": "500ms"
      },
      "transitionTimingFunction": {
        "linear": "linear",
        "ease": "ease",
        "ease-in": "ease-in",
        "ease-out": "ease-out",
        "ease-in-out": "ease-in-out"
      },
      "screens": {
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1536px"
      }
    }
  }
};
