/** @type {import('tailwindcss').Config} */
// Design Tokens - Auto-generated Tailwind Configuration
// Do not edit this file manually

export default {
  "theme": {
    "extend": {
      "colors": {
        "gray-50": "#f9fafb",
        "gray-100": "#f3f4f6",
        "gray-200": "#e5e7eb",
        "gray-300": "#d1d5db",
        "gray-400": "#9ca3af",
        "gray-500": "#6b7280",
        "gray-600": "#4b5563",
        "gray-700": "#374151",
        "gray-800": "#1f2937",
        "gray-900": "#111827",
        "blue-50": "#eff6ff",
        "blue-100": "#dbeafe",
        "blue-200": "#bfdbfe",
        "blue-300": "#93c5fd",
        "blue-400": "#60a5fa",
        "blue-500": "#3b82f6",
        "blue-600": "#2563eb",
        "blue-700": "#1d4ed8",
        "blue-800": "#1e40af",
        "blue-900": "#1e3a8a",
        "red-50": "#fef2f2",
        "red-100": "#fee2e2",
        "red-200": "#fecaca",
        "red-300": "#fca5a5",
        "red-400": "#f87171",
        "red-500": "#ef4444",
        "red-600": "#dc2626",
        "red-700": "#b91c1c",
        "red-800": "#991b1b",
        "red-900": "#7f1d1d",
        "green-50": "#f0fdf4",
        "green-100": "#dcfce7",
        "green-200": "#bbf7d0",
        "green-300": "#86efac",
        "green-400": "#4ade80",
        "green-500": "#22c55e",
        "green-600": "#16a34a",
        "green-700": "#15803d",
        "green-800": "#166534",
        "green-900": "#14532d",
        "text-primary": "{core.colors.gray.900}",
        "text-secondary": "{core.colors.gray.600}",
        "text-tertiary": "{core.colors.gray.400}",
        "text-inverse": "{core.colors.gray.50}",
        "background-primary": "{core.colors.gray.50}",
        "background-secondary": "{core.colors.gray.100}",
        "background-inverse": "{core.colors.gray.900}",
        "border-default": "{core.colors.gray.200}",
        "border-hover": "{core.colors.gray.300}",
        "border-focus": "{core.colors.blue.500}",
        "brand-primary": "{core.colors.blue.500}",
        "brand-secondary": "{core.colors.blue.600}",
        "brand-tertiary": "{core.colors.blue.100}",
        "feedback-success": "{core.colors.green.500}",
        "feedback-warning": "#f59e0b",
        "feedback-error": "{core.colors.red.500}",
        "feedback-info": "{core.colors.blue.500}"
      },
      "spacing": {
        "0": "0",
        "1": "0.25rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "8": "2rem",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem"
      },
      "borderRadius": {
        "none": "0",
        "sm": "0.125rem",
        "base": "0.25rem",
        "md": "0.375rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      "fontFamily": {
        "sans": [
          "Inter",
          "system-ui",
          "sans-serif"
        ],
        "mono": [
          "Fira Code",
          "Monaco",
          "Consolas",
          "monospace"
        ]
      },
      "fontSize": {
        "xs": "0.75rem",
        "sm": "0.875rem",
        "base": "1rem",
        "lg": "1.125rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "1.875rem",
        "4xl": "2.25rem",
        "5xl": "3rem"
      },
      "fontWeight": {
        "normal": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700"
      },
      "lineHeight": {
        "tight": "1.25",
        "normal": "1.5",
        "relaxed": "1.75"
      },
      "boxShadow": {
        "sm": "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "base": "0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)",
        "md": "0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)",
        "lg": "0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)",
        "xl": "0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)"
      },
      "opacity": {
        "0": "0",
        "25": "0.25",
        "50": "0.5",
        "75": "0.75",
        "100": "1"
      },
      "zIndex": {
        "auto": 0,
        "base": 1,
        "dropdown": 1000,
        "modal": 1040,
        "popover": 1050,
        "tooltip": 1060
      },
      "transitionDuration": {
        "fast": "150ms",
        "normal": "300ms",
        "slow": "500ms"
      },
      "transitionTimingFunction": {
        "linear": "linear",
        "ease": "ease",
        "ease-in": "ease-in",
        "ease-out": "ease-out",
        "ease-in-out": "ease-in-out"
      },
      "screens": {
        "sm": "640px",
        "md": "768px",
        "lg": "1024px",
        "xl": "1280px",
        "2xl": "1536px"
      }
    }
  }
};
