// Design Tokens - Auto-generated SwiftUI
// Do not edit this file manually

import SwiftUI

struct DesignTokens {
    struct Colors {
        static let primary50 = Color(red: 0.969, green: 0.914, blue: 0.949)
        static let primary100 = Color(red: 0.941, green: 0.827, blue: 0.902)
        static let primary200 = Color(red: 0.910, green: 0.741, blue: 0.851)
        static let primary300 = Color(red: 0.878, green: 0.655, blue: 0.804)
        static let primary400 = Color(red: 0.851, green: 0.569, blue: 0.757)
        static let primary500 = Color(red: 0.404, green: 0.200, blue: 0.569)
        static let primary600 = Color(red: 0.463, green: 0.278, blue: 0.608)
        static let primary700 = Color(red: 0.514, green: 0.353, blue: 0.647)
        static let primary800 = Color(red: 0.573, green: 0.431, blue: 0.690)
        static let primary900 = Color(red: 0.310, green: 0.157, blue: 0.435)
        static let accent50 = Color(red: 0.969, green: 0.914, blue: 0.949)
        static let accent100 = Color(red: 0.941, green: 0.827, blue: 0.902)
        static let accent200 = Color(red: 0.910, green: 0.741, blue: 0.851)
        static let accent300 = Color(red: 0.878, green: 0.655, blue: 0.804)
        static let accent400 = Color(red: 0.851, green: 0.569, blue: 0.757)
        static let accent500 = Color(red: 0.698, green: 0.137, blue: 0.510)
        static let accent600 = Color(red: 0.729, green: 0.224, blue: 0.561)
        static let accent700 = Color(red: 0.788, green: 0.396, blue: 0.655)
        static let accent800 = Color(red: 0.478, green: 0.063, blue: 0.341)
        static let accent900 = Color(red: 0.478, green: 0.063, blue: 0.341)
        static let success50 = Color(red: 0.902, green: 0.957, blue: 0.925)
        static let success100 = Color(red: 0.176, green: 0.525, blue: 0.349)
        static let success200 = Color(red: 0.318, green: 0.627, blue: 0.216)
        static let success300 = Color(red: 0.243, green: 0.490, blue: 0.169)
        static let warning50 = Color(red: 1.000, green: 0.973, blue: 0.882)
        static let warning100 = Color(red: 1.000, green: 0.596, blue: 0.000)
        static let error50 = Color(red: 0.988, green: 0.941, blue: 0.933)
        static let error100 = Color(red: 0.792, green: 0.451, blue: 0.451)
        static let error200 = Color(red: 0.980, green: 0.929, blue: 0.929)
        static let error300 = Color(red: 0.635, green: 0.184, blue: 0.184)
        static let neutral50 = Color(red: 1.000, green: 1.000, blue: 1.000)
        static let neutral100 = Color(red: 0.980, green: 0.980, blue: 0.980)
        static let neutral200 = Color(red: 0.953, green: 0.973, blue: 0.988)
        static let neutral300 = Color(red: 0.941, green: 0.965, blue: 0.980)
        static let neutral400 = Color(red: 0.980, green: 0.992, blue: 1.000)
        static let neutral500 = Color(red: 0.906, green: 0.929, blue: 0.941)
        static let neutral600 = Color(red: 0.565, green: 0.608, blue: 0.667)
        static let neutral700 = Color(red: 0.459, green: 0.459, blue: 0.459)
        static let neutral800 = Color(red: 0.439, green: 0.518, blue: 0.592)
        static let neutral900 = Color(red: 0.000, green: 0.000, blue: 0.000)
        static let statusSuccess = Color(red: 0.176, green: 0.525, blue: 0.349)
        static let statusWarning = Color(red: 1.000, green: 0.596, blue: 0.000)
        static let statusError = Color(red: 0.792, green: 0.451, blue: 0.451)
        static let statusInfo = Color(red: 0.729, green: 0.224, blue: 0.561)
        static let statusVerified = Color(red: 0.318, green: 0.627, blue: 0.216)
    }

    struct Spacing {
        static let _0: CGFloat = 0
        static let _1: CGFloat = 4
        static let _2: CGFloat = 8
        static let _3: CGFloat = 12
        static let _4: CGFloat = 16
        static let _5: CGFloat = 20
        static let _6: CGFloat = 24
        static let _8: CGFloat = 32
        static let _10: CGFloat = 40
        static let _12: CGFloat = 48
        static let _16: CGFloat = 64
        static let _20: CGFloat = 80
        static let _24: CGFloat = 96
    }

    struct FontSize {
        static let xs: CGFloat = 12
        static let sm: CGFloat = 14
        static let base: CGFloat = 16
        static let lg: CGFloat = 18
        static let xl: CGFloat = 20
        static let _2xl: CGFloat = 24
        static let _3xl: CGFloat = 30
        static let _4xl: CGFloat = 36
        static let _5xl: CGFloat = 48
    }

    struct FontFamily {
    }

    struct BorderRadius {
        static let none: CGFloat = 0
        static let sm: CGFloat = 2
        static let base: CGFloat = 4
        static let md: CGFloat = 6
        static let lg: CGFloat = 8
        static let xl: CGFloat = 12
        static let _2xl: CGFloat = 16
        static let full: CGFloat = 9999
    }

}