// Design Tokens - Auto-generated React Native Styles
// Do not edit this file manually

export const colors = {
  primary: {
    _50: '#F8FEFF',
    _100: '#F0F9FF',
    _200: '#E5F5FF',
    _300: '#C3E7FF',
    _400: '#C1E4FB',
    _500: '#0F3340',
    _600: '#0F1F40',
    _700: '#0074A5',
    _800: '#556A7D',
    _900: '#475A66',
  },
  gray: {
    _50: '#FFFFFF',
    _100: '#FAFAFA',
    _200: '#F3F8FC',
    _300: '#F0F6FA',
    _400: '#FAFDFF',
    _500: '#E7EDF0',
    _600: '#909BAA',
    _700: '#757575',
    _800: '#708497',
    _900: '#000000',
  },
  success: {
    _50: '#E6F4EC',
    _100: '#2D8659',
  },
  warning: {
    _50: '#E0F5FF',
    _100: '#0074A5',
  },
  error: {
    _50: '#FCF0EE',
    _100: '#CA7373',
    _200: '#FAEDED',
    _300: '#A22F2F',
  },
  info: {
    _50: '#F9ECF3',
    _100: '#7C3A60',
  },
  neutral: {
    _50: '#FFF1DF',
    _100: '#AC732B',
    _200: '#F7EFE4',
    _300: '#7A5E3A',
  },
  text: {
    primary: '#0F3340',
    secondary: '#757575',
    tertiary: '#909BAA',
    inverse: '#FFFFFF',
    muted: '#708497',
  },
  background: {
    primary: '#F8FEFF',
    secondary: '#FFFFFF',
    tertiary: '#F3F8FC',
    inverse: '#0F3340',
  },
  border: {
    default: '#E7EDF0',
    hover: '#C1E4FB',
    focus: '#0F3340',
    light: '#E7EDF0',
  },
  brand: {
    primary: '#0F3340',
    secondary: '#0F1F40',
    tertiary: '#E5F5FF',
  },
  feedback: {
    success: '#2D8659',
    successBg: '#E6F4EC',
    warning: '#0074A5',
    warningBg: '#E0F5FF',
    error: '#CA7373',
    errorBg: '#FCF0EE',
    info: '#7C3A60',
    infoBg: '#F9ECF3',
    neutral: '#AC732B',
    neutralBg: '#FFF1DF',
  },
};

export const spacing = {
  _0: 0,
  _1: 4,
  _2: 8,
  _3: 12,
  _4: 16,
  _5: 20,
  _6: 24,
  _8: 32,
  _10: 40,
  _12: 48,
  _16: 64,
  _20: 80,
  _24: 96,
};

export const fontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  _2xl: 24,
  _3xl: 30,
  _4xl: 36,
  _5xl: 48,
};

export const fontFamily = {
};

export const borderRadius = {
  none: 0,
  sm: 2,
  base: 4,
  md: 6,
  lg: 8,
  xl: 12,
  _2xl: 16,
  full: 9999,
};

export const shadows = {
  sm: {
        "shadowOffset": {
            "width": 0,
            "height": 1
        },
        "shadowRadius": 2,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 2
    },
  base: {
        "shadowOffset": {
            "width": 0,
            "height": 1
        },
        "shadowRadius": 3,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 2
    },
  md: {
        "shadowOffset": {
            "width": 0,
            "height": 4
        },
        "shadowRadius": 6,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 3
    },
  lg: {
        "shadowOffset": {
            "width": 0,
            "height": 10
        },
        "shadowRadius": 15,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 7.5
    },
  xl: {
        "shadowOffset": {
            "width": 0,
            "height": 20
        },
        "shadowRadius": 25,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 12.5
    },
};

export const tokens = {
  colors,
  spacing,
  fontSize,
  fontFamily,
  borderRadius,
  shadows,
};

export default tokens;