// Design Tokens - Auto-generated React Native Styles
// Do not edit this file manually

export const colors = {
  primary: {
    _50: '#F7E9F2',
    _100: '#F0D3E6',
    _200: '#E8BDD9',
    _300: '#E0A7CD',
    _400: '#D991C1',
    _500: '#673391',
    _600: '#76479B',
    _700: '#835AA5',
    _800: '#926EB0',
    _900: '#4F286F',
  },
  accent: {
    _50: '#F7E9F2',
    _100: '#F0D3E6',
    _200: '#E8BDD9',
    _300: '#E0A7CD',
    _400: '#D991C1',
    _500: '#B22382',
    _600: '#BA398F',
    _700: '#C965A7',
    _800: '#7A1057',
    _900: '#7A1057',
  },
  success: {
    _50: '#E6F4EC',
    _100: '#2D8659',
    _200: '#51A037',
    _300: '#3E7D2B',
  },
  warning: {
    _50: '#FFF8E1',
    _100: '#FF9800',
  },
  error: {
    _50: '#FCF0EE',
    _100: '#CA7373',
    _200: '#FAEDED',
    _300: '#A22F2F',
  },
  neutral: {
    _50: '#FFFFFF',
    _100: '#FAFAFA',
    _200: '#F3F8FC',
    _300: '#F0F6FA',
    _400: '#FAFDFF',
    _500: '#E7EDF0',
    _600: '#909BAA',
    _700: '#757575',
    _800: '#708497',
    _900: '#000000',
  },
  status: {
    success: '#2D8659',
    warning: '#FF9800',
    error: '#CA7373',
    info: '#BA398F',
    verified: '#51A037',
  },
};

export const spacing = {
  _0: 0,
  _1: 4,
  _2: 8,
  _3: 12,
  _4: 16,
  _5: 20,
  _6: 24,
  _8: 32,
  _10: 40,
  _12: 48,
  _16: 64,
  _20: 80,
  _24: 96,
};

export const fontSize = {
  xs: 12,
  sm: 14,
  base: 16,
  lg: 18,
  xl: 20,
  _2xl: 24,
  _3xl: 30,
  _4xl: 36,
  _5xl: 48,
};

export const fontFamily = {
};

export const borderRadius = {
  none: 0,
  sm: 2,
  base: 4,
  md: 6,
  lg: 8,
  xl: 12,
  _2xl: 16,
  full: 9999,
};

export const shadows = {
  sm: {
        "shadowOffset": {
            "width": 0,
            "height": 1
        },
        "shadowRadius": 2,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 2
    },
  base: {
        "shadowOffset": {
            "width": 0,
            "height": 1
        },
        "shadowRadius": 3,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 2
    },
  md: {
        "shadowOffset": {
            "width": 0,
            "height": 4
        },
        "shadowRadius": 6,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 3
    },
  lg: {
        "shadowOffset": {
            "width": 0,
            "height": 10
        },
        "shadowRadius": 15,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 7.5
    },
  xl: {
        "shadowOffset": {
            "width": 0,
            "height": 20
        },
        "shadowRadius": 25,
        "shadowColor": "#000000",
        "shadowOpacity": 1,
        "elevation": 12.5
    },
};

export const tokens = {
  colors,
  spacing,
  fontSize,
  fontFamily,
  borderRadius,
  shadows,
};

export default tokens;