// Design Tokens - Auto-generated TypeScript Definitions
// Do not edit this file manually

export interface Colors {
  primary: {
    "50": string;
    "100": string;
    "200": string;
    "300": string;
    "400": string;
    "500": string;
    "600": string;
    "700": string;
    "800": string;
    "900": string;
  };
  gray: {
    "50": string;
    "100": string;
    "200": string;
    "300": string;
    "400": string;
    "500": string;
    "600": string;
    "700": string;
    "800": string;
    "900": string;
  };
  text: {
    "primary": string;
    "secondary": string;
    "inverse": string;
  };
  background: {
    "primary": string;
    "secondary": string;
  };
  border: {
    "default": string;
  };
  brand: {
    "primary": string;
    "secondary": string;
  };
}

export interface Spacing {
  "0": string;
  "1": string;
  "2": string;
  "3": string;
  "4": string;
}

export interface Typography {
  fontFamily: {
    "sans": string;
    "mono": string;
  };
  fontSize: {
  };
  fontWeight: {
  };
  lineHeight: {
  };
  letterSpacing: {
  };
}

export interface DesignTokens {
  colors: Colors;
  spacing: Spacing;
  typography: Typography;
  borderRadius: Record<string, string>;
  shadows: Record<string, string>;
  opacity: Record<string, string>;
  zIndex: Record<string, number>;
  transitions: {
    duration: Record<string, string>;
    easing: Record<string, string>;
  };
  breakpoints: Record<string, string>;
  source?: string;
  lastLoaded?: string;
}

// Token value constants
declare const tokens: DesignTokens;
export default tokens;
export const colors: Colors;
export const spacing: Spacing;
export const typography: Typography;
export const borderRadius: Record<string, string>;
export const shadows: Record<string, string>;
export const opacity: Record<string, string>;