// Design Tokens - Auto-generated Kotlin Compose
// Do not edit this file manually

package com.yourapp.designtokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
    object Colors {
        val Primary50 = Color(0xFFF8FEFF)
        val Primary100 = Color(0xFFF0F9FF)
        val Primary200 = Color(0xFFE5F5FF)
        val Primary300 = Color(0xFFC3E7FF)
        val Primary400 = Color(0xFFC1E4FB)
        val Primary500 = Color(0xFF0F3340)
        val Primary600 = Color(0xFF0F1F40)
        val Primary700 = Color(0xFF0074A5)
        val Primary800 = Color(0xFF556A7D)
        val Primary900 = Color(0xFF475A66)
        val Gray50 = Color(0xFFFFFFFF)
        val Gray100 = Color(0xFFFAFAFA)
        val Gray200 = Color(0xFFF3F8FC)
        val Gray300 = Color(0xFFF0F6FA)
        val Gray400 = Color(0xFFFAFDFF)
        val Gray500 = Color(0xFFE7EDF0)
        val Gray600 = Color(0xFF909BAA)
        val Gray700 = Color(0xFF757575)
        val Gray800 = Color(0xFF708497)
        val Gray900 = Color(0xFF000000)
        val Success50 = Color(0xFFE6F4EC)
        val Success100 = Color(0xFF2D8659)
        val Warning50 = Color(0xFFE0F5FF)
        val Warning100 = Color(0xFF0074A5)
        val Error50 = Color(0xFFFCF0EE)
        val Error100 = Color(0xFFCA7373)
        val Error200 = Color(0xFFFAEDED)
        val Error300 = Color(0xFFA22F2F)
        val Info50 = Color(0xFFF9ECF3)
        val Info100 = Color(0xFF7C3A60)
        val Neutral50 = Color(0xFFFFF1DF)
        val Neutral100 = Color(0xFFAC732B)
        val Neutral200 = Color(0xFFF7EFE4)
        val Neutral300 = Color(0xFF7A5E3A)
        val TextPrimary = Color(0xFF0F3340)
        val TextSecondary = Color(0xFF757575)
        val TextTertiary = Color(0xFF909BAA)
        val TextInverse = Color(0xFFFFFFFF)
        val TextMuted = Color(0xFF708497)
        val BackgroundPrimary = Color(0xFFF8FEFF)
        val BackgroundSecondary = Color(0xFFFFFFFF)
        val BackgroundTertiary = Color(0xFFF3F8FC)
        val BackgroundInverse = Color(0xFF0F3340)
        val BorderDefault = Color(0xFFE7EDF0)
        val BorderHover = Color(0xFFC1E4FB)
        val BorderFocus = Color(0xFF0F3340)
        val BorderLight = Color(0xFFE7EDF0)
        val BrandPrimary = Color(0xFF0F3340)
        val BrandSecondary = Color(0xFF0F1F40)
        val BrandTertiary = Color(0xFFE5F5FF)
        val FeedbackSuccess = Color(0xFF2D8659)
        val FeedbackSuccessBg = Color(0xFFE6F4EC)
        val FeedbackWarning = Color(0xFF0074A5)
        val FeedbackWarningBg = Color(0xFFE0F5FF)
        val FeedbackError = Color(0xFFCA7373)
        val FeedbackErrorBg = Color(0xFFFCF0EE)
        val FeedbackInfo = Color(0xFF7C3A60)
        val FeedbackInfoBg = Color(0xFFF9ECF3)
        val FeedbackNeutral = Color(0xFFAC732B)
        val FeedbackNeutralBg = Color(0xFFFFF1DF)
    }

    object Spacing {
        val 0 = 0.dp
        val 1 = 4.dp
        val 2 = 8.dp
        val 3 = 12.dp
        val 4 = 16.dp
        val 5 = 20.dp
        val 6 = 24.dp
        val 8 = 32.dp
        val 10 = 40.dp
        val 12 = 48.dp
        val 16 = 64.dp
        val 20 = 80.dp
        val 24 = 96.dp
    }

    object FontSize {
        val Xs = 12.sp
        val Sm = 14.sp
        val Base = 16.sp
        val Lg = 18.sp
        val Xl = 20.sp
        val 2xl = 24.sp
        val 3xl = 30.sp
        val 4xl = 36.sp
        val 5xl = 48.sp
    }

    object BorderRadius {
        val None = 0.dp
        val Sm = 2.dp
        val Base = 4.dp
        val Md = 6.dp
        val Lg = 8.dp
        val Xl = 12.dp
        val 2xl = 16.dp
        val Full = 9999.dp
    }

}