// Design Tokens - Auto-generated Kotlin Compose
// Do not edit this file manually

package com.yourapp.designtokens

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object DesignTokens {
    object Colors {
        val Primary50 = Color(0xFFF7E9F2)
        val Primary100 = Color(0xFFF0D3E6)
        val Primary200 = Color(0xFFE8BDD9)
        val Primary300 = Color(0xFFE0A7CD)
        val Primary400 = Color(0xFFD991C1)
        val Primary500 = Color(0xFF673391)
        val Primary600 = Color(0xFF76479B)
        val Primary700 = Color(0xFF835AA5)
        val Primary800 = Color(0xFF926EB0)
        val Primary900 = Color(0xFF4F286F)
        val Accent50 = Color(0xFFF7E9F2)
        val Accent100 = Color(0xFFF0D3E6)
        val Accent200 = Color(0xFFE8BDD9)
        val Accent300 = Color(0xFFE0A7CD)
        val Accent400 = Color(0xFFD991C1)
        val Accent500 = Color(0xFFB22382)
        val Accent600 = Color(0xFFBA398F)
        val Accent700 = Color(0xFFC965A7)
        val Accent800 = Color(0xFF7A1057)
        val Accent900 = Color(0xFF7A1057)
        val Success50 = Color(0xFFE6F4EC)
        val Success100 = Color(0xFF2D8659)
        val Success200 = Color(0xFF51A037)
        val Success300 = Color(0xFF3E7D2B)
        val Warning50 = Color(0xFFFFF8E1)
        val Warning100 = Color(0xFFFF9800)
        val Error50 = Color(0xFFFCF0EE)
        val Error100 = Color(0xFFCA7373)
        val Error200 = Color(0xFFFAEDED)
        val Error300 = Color(0xFFA22F2F)
        val Neutral50 = Color(0xFFFFFFFF)
        val Neutral100 = Color(0xFFFAFAFA)
        val Neutral200 = Color(0xFFF3F8FC)
        val Neutral300 = Color(0xFFF0F6FA)
        val Neutral400 = Color(0xFFFAFDFF)
        val Neutral500 = Color(0xFFE7EDF0)
        val Neutral600 = Color(0xFF909BAA)
        val Neutral700 = Color(0xFF757575)
        val Neutral800 = Color(0xFF708497)
        val Neutral900 = Color(0xFF000000)
        val StatusSuccess = Color(0xFF2D8659)
        val StatusWarning = Color(0xFFFF9800)
        val StatusError = Color(0xFFCA7373)
        val StatusInfo = Color(0xFFBA398F)
        val StatusVerified = Color(0xFF51A037)
    }

    object Spacing {
        val 0 = 0.dp
        val 1 = 4.dp
        val 2 = 8.dp
        val 3 = 12.dp
        val 4 = 16.dp
        val 5 = 20.dp
        val 6 = 24.dp
        val 8 = 32.dp
        val 10 = 40.dp
        val 12 = 48.dp
        val 16 = 64.dp
        val 20 = 80.dp
        val 24 = 96.dp
    }

    object FontSize {
        val Xs = 12.sp
        val Sm = 14.sp
        val Base = 16.sp
        val Lg = 18.sp
        val Xl = 20.sp
        val 2xl = 24.sp
        val 3xl = 30.sp
        val 4xl = 36.sp
        val 5xl = 48.sp
    }

    object BorderRadius {
        val None = 0.dp
        val Sm = 2.dp
        val Base = 4.dp
        val Md = 6.dp
        val Lg = 8.dp
        val Xl = 12.dp
        val 2xl = 16.dp
        val Full = 9999.dp
    }

}