// Design Tokens - Auto-generated Flutter/Dart
// Do not edit this file manually

import 'package:flutter/material.dart';

class DesignTokens {
  // Colors
  static class Colors {
    static const Color primary50 = Color(0xFFF8FEFF);
    static const Color primary100 = Color(0xFFF0F9FF);
    static const Color primary200 = Color(0xFFE5F5FF);
    static const Color primary300 = Color(0xFFC3E7FF);
    static const Color primary400 = Color(0xFFC1E4FB);
    static const Color primary500 = Color(0xFF0F3340);
    static const Color primary600 = Color(0xFF0F1F40);
    static const Color primary700 = Color(0xFF0074A5);
    static const Color primary800 = Color(0xFF556A7D);
    static const Color primary900 = Color(0xFF475A66);
    static const Color gray50 = Color(0xFFFFFFFF);
    static const Color gray100 = Color(0xFFFAFAFA);
    static const Color gray200 = Color(0xFFF3F8FC);
    static const Color gray300 = Color(0xFFF0F6FA);
    static const Color gray400 = Color(0xFFFAFDFF);
    static const Color gray500 = Color(0xFFE7EDF0);
    static const Color gray600 = Color(0xFF909BAA);
    static const Color gray700 = Color(0xFF757575);
    static const Color gray800 = Color(0xFF708497);
    static const Color gray900 = Color(0xFF000000);
    static const Color success50 = Color(0xFFE6F4EC);
    static const Color success100 = Color(0xFF2D8659);
    static const Color warning50 = Color(0xFFE0F5FF);
    static const Color warning100 = Color(0xFF0074A5);
    static const Color error50 = Color(0xFFFCF0EE);
    static const Color error100 = Color(0xFFCA7373);
    static const Color error200 = Color(0xFFFAEDED);
    static const Color error300 = Color(0xFFA22F2F);
    static const Color info50 = Color(0xFFF9ECF3);
    static const Color info100 = Color(0xFF7C3A60);
    static const Color neutral50 = Color(0xFFFFF1DF);
    static const Color neutral100 = Color(0xFFAC732B);
    static const Color neutral200 = Color(0xFFF7EFE4);
    static const Color neutral300 = Color(0xFF7A5E3A);
    static const Color textPrimary = Color(0xFF0F3340);
    static const Color textSecondary = Color(0xFF757575);
    static const Color textTertiary = Color(0xFF909BAA);
    static const Color textInverse = Color(0xFFFFFFFF);
    static const Color textMuted = Color(0xFF708497);
    static const Color backgroundPrimary = Color(0xFFF8FEFF);
    static const Color backgroundSecondary = Color(0xFFFFFFFF);
    static const Color backgroundTertiary = Color(0xFFF3F8FC);
    static const Color backgroundInverse = Color(0xFF0F3340);
    static const Color borderDefault = Color(0xFFE7EDF0);
    static const Color borderHover = Color(0xFFC1E4FB);
    static const Color borderFocus = Color(0xFF0F3340);
    static const Color borderLight = Color(0xFFE7EDF0);
    static const Color brandPrimary = Color(0xFF0F3340);
    static const Color brandSecondary = Color(0xFF0F1F40);
    static const Color brandTertiary = Color(0xFFE5F5FF);
    static const Color feedbackSuccess = Color(0xFF2D8659);
    static const Color feedbackSuccessBg = Color(0xFFE6F4EC);
    static const Color feedbackWarning = Color(0xFF0074A5);
    static const Color feedbackWarningBg = Color(0xFFE0F5FF);
    static const Color feedbackError = Color(0xFFCA7373);
    static const Color feedbackErrorBg = Color(0xFFFCF0EE);
    static const Color feedbackInfo = Color(0xFF7C3A60);
    static const Color feedbackInfoBg = Color(0xFFF9ECF3);
    static const Color feedbackNeutral = Color(0xFFAC732B);
    static const Color feedbackNeutralBg = Color(0xFFFFF1DF);
  }

  // Spacing
  static class Spacing {
    static const double _0 = 0;
    static const double _1 = 4;
    static const double _2 = 8;
    static const double _3 = 12;
    static const double _4 = 16;
    static const double _5 = 20;
    static const double _6 = 24;
    static const double _8 = 32;
    static const double _10 = 40;
    static const double _12 = 48;
    static const double _16 = 64;
    static const double _20 = 80;
    static const double _24 = 96;
  }

  // Font Sizes
  static class FontSize {
    static const double xs = 12;
    static const double sm = 14;
    static const double base = 16;
    static const double lg = 18;
    static const double xl = 20;
    static const double _2xl = 24;
    static const double _3xl = 30;
    static const double _4xl = 36;
    static const double _5xl = 48;
  }

  // Font Families
  static class FontFamily {
  }

  // Border Radius
  static class BorderRadius {
    static const double none = 0;
    static const double sm = 2;
    static const double base = 4;
    static const double md = 6;
    static const double lg = 8;
    static const double xl = 12;
    static const double _2xl = 16;
    static const double full = 9999;
  }

  // Shadows
  static class Shadows {
    static const BoxShadow sm = BoxShadow(
      offset: Offset(0, 1),
      blurRadius: 2,
      color: Color(0xFF000000),
    );
    static const BoxShadow base = BoxShadow(
      offset: Offset(0, 1),
      blurRadius: 3,
      color: Color(0xFF000000),
    );
    static const BoxShadow md = BoxShadow(
      offset: Offset(0, 4),
      blurRadius: 6,
      color: Color(0xFF000000),
    );
    static const BoxShadow lg = BoxShadow(
      offset: Offset(0, 10),
      blurRadius: 15,
      color: Color(0xFF000000),
    );
    static const BoxShadow xl = BoxShadow(
      offset: Offset(0, 20),
      blurRadius: 25,
      color: Color(0xFF000000),
    );
  }

}