// Design Tokens - Auto-generated Flutter/Dart
// Do not edit this file manually

import 'package:flutter/material.dart';

class DesignTokens {
  // Colors
  static class Colors {
    static const Color primary50 = Color(0xFFF7E9F2);
    static const Color primary100 = Color(0xFFF0D3E6);
    static const Color primary200 = Color(0xFFE8BDD9);
    static const Color primary300 = Color(0xFFE0A7CD);
    static const Color primary400 = Color(0xFFD991C1);
    static const Color primary500 = Color(0xFF673391);
    static const Color primary600 = Color(0xFF76479B);
    static const Color primary700 = Color(0xFF835AA5);
    static const Color primary800 = Color(0xFF926EB0);
    static const Color primary900 = Color(0xFF4F286F);
    static const Color accent50 = Color(0xFFF7E9F2);
    static const Color accent100 = Color(0xFFF0D3E6);
    static const Color accent200 = Color(0xFFE8BDD9);
    static const Color accent300 = Color(0xFFE0A7CD);
    static const Color accent400 = Color(0xFFD991C1);
    static const Color accent500 = Color(0xFFB22382);
    static const Color accent600 = Color(0xFFBA398F);
    static const Color accent700 = Color(0xFFC965A7);
    static const Color accent800 = Color(0xFF7A1057);
    static const Color accent900 = Color(0xFF7A1057);
    static const Color success50 = Color(0xFFE6F4EC);
    static const Color success100 = Color(0xFF2D8659);
    static const Color success200 = Color(0xFF51A037);
    static const Color success300 = Color(0xFF3E7D2B);
    static const Color warning50 = Color(0xFFFFF8E1);
    static const Color warning100 = Color(0xFFFF9800);
    static const Color error50 = Color(0xFFFCF0EE);
    static const Color error100 = Color(0xFFCA7373);
    static const Color error200 = Color(0xFFFAEDED);
    static const Color error300 = Color(0xFFA22F2F);
    static const Color neutral50 = Color(0xFFFFFFFF);
    static const Color neutral100 = Color(0xFFFAFAFA);
    static const Color neutral200 = Color(0xFFF3F8FC);
    static const Color neutral300 = Color(0xFFF0F6FA);
    static const Color neutral400 = Color(0xFFFAFDFF);
    static const Color neutral500 = Color(0xFFE7EDF0);
    static const Color neutral600 = Color(0xFF909BAA);
    static const Color neutral700 = Color(0xFF757575);
    static const Color neutral800 = Color(0xFF708497);
    static const Color neutral900 = Color(0xFF000000);
    static const Color statusSuccess = Color(0xFF2D8659);
    static const Color statusWarning = Color(0xFFFF9800);
    static const Color statusError = Color(0xFFCA7373);
    static const Color statusInfo = Color(0xFFBA398F);
    static const Color statusVerified = Color(0xFF51A037);
  }

  // Spacing
  static class Spacing {
    static const double _0 = 0;
    static const double _1 = 4;
    static const double _2 = 8;
    static const double _3 = 12;
    static const double _4 = 16;
    static const double _5 = 20;
    static const double _6 = 24;
    static const double _8 = 32;
    static const double _10 = 40;
    static const double _12 = 48;
    static const double _16 = 64;
    static const double _20 = 80;
    static const double _24 = 96;
  }

  // Font Sizes
  static class FontSize {
    static const double xs = 12;
    static const double sm = 14;
    static const double base = 16;
    static const double lg = 18;
    static const double xl = 20;
    static const double _2xl = 24;
    static const double _3xl = 30;
    static const double _4xl = 36;
    static const double _5xl = 48;
  }

  // Font Families
  static class FontFamily {
  }

  // Border Radius
  static class BorderRadius {
    static const double none = 0;
    static const double sm = 2;
    static const double base = 4;
    static const double md = 6;
    static const double lg = 8;
    static const double xl = 12;
    static const double _2xl = 16;
    static const double full = 9999;
  }

  // Shadows
  static class Shadows {
    static const BoxShadow sm = BoxShadow(
      offset: Offset(0, 1),
      blurRadius: 2,
      color: Color(0xFF000000),
    );
    static const BoxShadow base = BoxShadow(
      offset: Offset(0, 1),
      blurRadius: 3,
      color: Color(0xFF000000),
    );
    static const BoxShadow md = BoxShadow(
      offset: Offset(0, 4),
      blurRadius: 6,
      color: Color(0xFF000000),
    );
    static const BoxShadow lg = BoxShadow(
      offset: Offset(0, 10),
      blurRadius: 15,
      color: Color(0xFF000000),
    );
    static const BoxShadow xl = BoxShadow(
      offset: Offset(0, 20),
      blurRadius: 25,
      color: Color(0xFF000000),
    );
  }

}